import DefinitionCard from "../components/DefinitionCard";
import Image from "next/image";

export default function DefinitionsPage() {
  // Example definitions - replace with your actual definitions
  const definitions = [
    {
      number: 1,
      term: "Group",
      definition: `\\text{A group is a set } G 
                   \\\\ \\text{along with a binary operation } * \\text{ such that:} 
                   \\\\ \\quad 1. \\text{ (Closure) } \\forall a, b \\in G, a * b \\in G 
                   \\\\ \\quad 2. \\text{ (Associativity) } \\forall a, b, c \\in G, (a * b) * c = a * (b * c) 
                   \\\\ \\quad 3. \\text{ (Identity) } \\exists e \\in G \\text{ such that } \\forall a \\in G, e * a = a * e = a 
                   \\\\ \\quad 4. \\text{ (Inverse) } \\forall a \\in G, \\exists a^{-1} \\in G 
                   \\\\ \\quad \\quad \\text{ such that } a * a^{-1} = a^{-1} * a = e,`,
    },
    {
      number: 2,
      term: "Subgroup",
      definition: "\\text{Let } G \\text{ be a group. A subset } H \\subseteq G \\text{ is a subgroup if:} \\\\ \\quad 1. \\text{ The identity } e \\in H \\\\ \\quad 2. \\text{ If } a, b \\in H, \\text{ then } ab \\in H \\\\ \\quad 3. \\text{ If } a \\in H, \\text{ then } a^{-1} \\in H",
    },
    {
      number: 3,
      term: "Homomorphism",
      definition: `\\text{Let } G \\text{ and } K \\text{ be two groups.}
                   \\\\ \\text{A map } \\phi: G \\to K \\text{ is called a homomorphism}
                   \\\\ \\text{if } \\forall a, b \\in G, \\phi(ab) = \\phi(a)\\phi(b)
                   \\\\ \\
                   \\\\ \\text{To be homomorphic haiku:}
                   \\\\ \\
                   \\\\ \\text{operate then map}
                   \\\\ \\text{must give the same result as}
                   \\\\ \\text{map then operate}
      `,
    },
    {
      number: 4,
      term: "Isomorphism",
      definition: `\\text{An isomorphism is a bijective homomorphism.}
                   \\\\ \\text{Written as } G \\cong K, \\text{ where } G \\text{ and } K \\text{ are groups}.
      `
    },
    {
      number: 5,
      term: "Kernel of a Homomorphism",
      definition: `\\text{Let } \\phi: G \\to K \\text{ be a homomorphism} 
                   \\\\ \\text{between groups } G \\text{ and } K.
                   \\\\ \\text{The kernel of } \\phi \\text{ is the set:}
                   \\\\ \\ker(\\phi) = \\{ x \\in G \\ | \\ \\phi(x) = e_K \\}`,
    },
    {
      number: 6,
      term: "Normal Subgroup",
      definition: `\\text{A subgroup } H \\text{ of a group } G \\text{ is called normal }( H \\trianglelefteq G )
                   \\\\ \\text{if } \\forall g \\in G, \\forall h \\in H, ghg^{-1} \\in H.
                   \\\\ \\
                   \\\\ H \\trianglelefteq G \\text{ if } H \\subseteq G.
                   \\\\ H \\triangleleft G \\text{ if } H \\subset G.
                  `,
    },
    {
      number: 7,
      term: "Generating Set",
      definition: `\\text{Let } G \\text{ be a group and let } S \\subseteq G \\text{ be nonempty.}
                   \\\\ \\text{Denote } S^{-1} = \\{ a^{-1} | a \\in S \\}.
                   \\\\ \\text{Then } \\langle S \\rangle = \\{x_1x_2 ... x_n \\ | \\ n \\in \\N, x_i \\in S \\cup S^{-1} \\cup \\{e\\}\\}.
                   \\\\ \\
                   \\\\ \\langle S \\rangle \\text{ is created by choosing different } n \\text{'s} 
                   \\\\ \\text{and finding the product of 1 through n elements of } 
                   \\\\ S \\cup S^{-1} \\cup \\{e\\}.
                   \\\\ \\
                   \\\\ \\text{For a single element:}
                   \\\\ \\langle g \\rangle = \\{g^n \\ | \\ n \\in \\Z \\}
      `
    },
    {
      number: 8,
      term: "Finitely Generated Group",
      definition: `\\text{A group is finitely generated if}
                   \\\\ \\text{there exists a finite nonempty subset of } S 
                   \\\\ \\text{s.t. } G \\text{ is generated by } S.
                   \\\\ \\text{In other words, } G = \\langle S \\rangle.
      `
    },
    {
      number: 9,
      term: "Cyclic Group",
      definition: `\\text{A group } G \\text{ is cyclic if }
                   \\\\ \\text{the group is generated by a single element. }
                   \\\\ \\text{i.e. if } G = \\langle a \\rangle \\text{ for some } a \\in G.
      `
    },
    {
      number: 10,
      term: "Relation",
      definition: `\\text{Let } X \\text{ be a set.}
                   \\\\ \\text{A relation on X is a subset of } X \\times X.
                   \\\\ \\
                   \\\\ \\text{In other words, a relation is an ordered pair}.
                   \\\\ \\
                   \\\\ \\text{For example, the point } (1, 2) \\text{ relates 1 and 2 in } \\R^2.
                   \\\\ \\text{You would write } 1 \\sim 2 \\text{ in this case.}
      `
    },
    {
      number: 11,
      term: "Properties of Relations",
      definition: `\\def\\circled#1{\\raisebox{.5pt}{\\textcircled{\\raisebox{-.9pt} {#1}}}}

                   \\text{A relation on } X \\text{ is said to be:}
                   \\\\ \\circled{1} \\text{ reflexive: if } x \\sim x \\ \\ \\forall x \\in X
                   \\\\ \\circled{2} \\text{ symmetric: if } x \\sim y \\implies y \\sim x \\ \\ \\forall x,y \\in X.
                   \\\\ \\circled{3} \\text{ transitive: if } x \\sim y \\wedge y \\sim z \\implies x \\sim z
                   \\\\ \\ \\ \\ \\ \\ \\forall x, y, z \\in X
                   \\\\ \\circled{4} \\text{ anti-symmetric: if } x \\sim y \\wedge y \\sim x \\implies x = y 
                   \\\\ \\ \\ \\ \\ \\ \\forall x, y \\in X.
      `
    },
    {
      number: 12,
      term: "Order Relation",
      definition: `\\text{An order relation (or partial order) on } X
                   \\\\ \\text{is a relation that is reflexive, antisymmetric, and transitive.}
                   \\\\ \\
                   \\\\ a \\leq b \\text{ and } a \\ | \\ b \\text{ (a "divides" b)}
                   \\\\ \\text{are examples of order relations.}
      `
    },
    {
      number: 13,
      term: "Equivalence Relation",
      definition: `\\text{An equivalence relation on } X
                   \\\\ \\text{is a relation that is reflexive, symmetric, and transitive.}
                   \\\\ \\
                   \\\\ \\text{For example,} 
                   \\\\ \\text{say two M} \\& \\text{Ms are the same if they have the same color}
                   \\\\ \\text{This is denoted as } a \\sim b \\iff (a \\text{ has same color as } b).
                   \\\\ \\
                   \\\\ \\text{Considering different equivalence relations on a set} 
                   \\\\ \\text{gives different partitions.}
                   \\\\ \\text{So a single set can be observed in many different ways.}
      `
    },
    {
      number: 14,
      term: "Equivalence Class",
      definition: `\\text{Given an equivalence relation } \\sim \\text{ on a set } X, 
                  \\\\ \\text{the equivalence class of } x \\in X \\text{ is the set:}
                  \\\\ [x] = \\{ y \\in X \\ | \\ x \\sim y \\}
                  \\\\ \\
                  \\\\ \\text{This was presented as a theorem:}
                  \\\\ \\quad 1) \\ \\ \\forall x, y \\in X
                  \\\\ \\quad \\quad \\ \\ \\text{if } x \\sim y \\text{ then } [x] = [y]
                  \\\\ \\quad \\quad \\ \\ \\text{if } x \\not \\sim y \\text{ then } [x] \\cap [y]  = \\empty.
                  \\\\ \\quad 2) \\ \\ \\bigcup_{x \\in X} [x] = X.
                  `
    },
    {
      number: 15,
      term: "Left Coset",
      definition: `\\text{Let } H \\leq G \\text{ and } x \\in G.
                   \\\\ \\text{The set } \\{ xh \\ | \\ h \\in H \\} \\text{ is called the left coset by } x.
                   \\\\ \\text{Written as } xH.
      `
    },
    {
      number: 16,
      term: "Automorphism",
      definition: `\\text{An automorphism is an isomorphism that maps from } G \\text{ to } G.
                   \\\\ \\text{Aut}(G) \\text{ is the set of all automorphisms of G.}
      `
    },
    {
      number: 17,
      term: "Inner Automorphism",
      definition: `\\text{An inner automorphism is an automorphism } 
                   \\\\ \\text{of the form } \\phi_g: G \\to G, 
                   \\\\ \\text{defined by } \\phi_g(x) = gxg^{-1} \\ \\text{ for } x, g \\in G.
                   \\\\ \\
                   \\\\ \\text{We denote }\\text{Inn}(G) = \\{\\phi_g \\ | \\ g \\in G \\} 
                   \\\\ \\text{as the set of all inner automorphisms of } G.
      `
    },
    {
      number: 18,
      term: "Symmetric Group",
      definition: `\\text{Let } X \\text{ be a set. Let } S_X = \\{f: X \\to X \\ | \\ f \\text{ is bijective} \\}.
                   \\\\ S_X \\text{ with composition is called the symmetric group.} 
                   \\\\ \\
                   \\\\ \\text{For } n \\in \\N \\text{ and } X = \\{ 1, 2, ..., n \\},  
                   \\\\ \\text{We denote } S_n \\text{ for } S_X.
                   \\\\ \\
                   \\\\ \\text{For example, } 
                   \\\\ S_2 \\text{ is the group of bijective functions over }
                   \\\\ X = \\{ 1, 2 \\}, \\text{and only has two elements:}
                   \\\\ \\text{the identity function and a single transposition}.
                   \\\\ \\text{In other words the only actions you can do in } S_2 
                   \\\\ \\text{is stay in place or swap places.}
                   \\\\ \\
                   \\\\ \\text{Even more generally,} 
                   \\\\ S_n \\text{ has } n! \\text{ permutations.}
      `
    },
    {
      number: 19,
      term: "Permutation",
      definition: `\\text{A permutation is a bijective mapping from a set onto itself}
      `
    },
    {
      number: 20,
      term: "Cycles",
      definition: `\\text{A cycle is a simple way to represent a permutation.}
                   \\\\ \\
                   \\\\ \\text{Given a permutation } \\sigma \\in S_4,
                   \\\\ \\text{Define } \\sigma = (1 \\ 2 \\ 3 \\ 4)
                   \\\\ \\text{This notation means } 
                   \\\\ 1 \\to 2
                   \\\\ 2 \\to 3
                   \\\\ 3 \\to 4
                   \\\\ 4 \\to 1
                   \\\\ \\
                   \\\\ \\sigma = (1 \\ 2) (3 \\ 4) \\text{ means}
                   \\\\ 1 \\to 2
                   \\\\ 2 \\to 1
                   \\\\ 3 \\to 4 
                   \\\\ 4 \\to 3
                   \\\\ \\
                   \\\\ \\sigma = (1 \\ 2) \\text{ means}
                   \\\\ 1 \\to 2
                   \\\\ 2 \\to 1
                   \\\\ 3 \\to 3 
                   \\\\ 4 \\to 4
                
      `
    },
    {
      number: 21,
      term: "Cycle Multiplication",
      definition: `\\text{To multiply cycles you compose the two permutations}
                   \\\\ \\sigma \\tau \\text{ can be read as apply } \\sigma \\text{ and then apply } \\tau.
                   \\\\ \\
                   \\\\ \\text{Let } \\sigma, \\tau \\in S_4 \\text{ with}
                   \\\\ \\sigma = (a \\ b \\ c \\ d) \\text{ and } \\tau = (a \\ d)(b \\ c).
                   
                   \\\\ \\
                   \\\\ \\text{To find } \\sigma \\tau,
                   \\\\ \\text{we evaluate } \\tau \\circ \\sigma \\text{ or } \\tau(\\sigma).
                   \\\\ \\text{Can be written as } ((a \\ d)(b \\ c))(a \\ b \\ c \\ d).
                   \\\\ \\
                   \\\\ \\text{Starting with } a \\text{ the first element in } \\sigma,
                   \\\\ a \\xrightarrow{\\sigma} b \\text{ then } b \\xrightarrow{\\tau} c
                   \\\\ c \\xrightarrow{\\sigma} d \\text{ then } d \\xrightarrow{\\tau} a
                   \\\\ \\text{This means } a \\text{ and } c \\text{ forms a cycle } (a \\ c).
                   \\\\ \\text{Now we go to the next element we haven't evaluated.}
                   \\\\ b \\xrightarrow{\\sigma} c \\text{ then } c \\xrightarrow{\\tau} b.
                   \\\\ \\text{So } b \\text{ is in a 1-cycle, because it maps to itself.}
                   \\\\ \\text{Finally we evaluate } d,
                   \\\\ d \\xrightarrow{\\sigma} a \\text{ then } a \\xrightarrow{\\tau} d.
                   \\\\ \\text{Therefore, our final product is } 
                   \\\\ (a \\ c).

      `,
      image: "/cycle-multiplication.svg",
      imageAlt: "Cycle multiplication diagram"
    },
    {
      number: 22,
      term: "Transposition",
      definition: `\\text{Let } n \\geq 2.
                   \\\\ \\text{A transposition is a permutation } \\tau \\in S_n
                   \\\\ \\text{of the form } (i \\ j) \\text{ for } 1 \\leq i \\neq j \\leq n.

      `
    },
    {
      number: 23,
      term: "Even or Odd Permutation",
      definition: `\\text{A permutation is called even if}
                   \\\\ \\text{it is a product of an even number of transpositions.}
                   \\\\ \\
                   \\\\ \\text{A permutation is called odd if}
                   \\\\ \\text{it is a product of an odd number of transpositions.}
      `
    },
    {
      number: 24,
      term: "Index",
      definition: `\\text{Let } H \\leq G. 
                   \\\\ \\text{The index of H in G is} 
                   \\\\ \\text{the cardinality of the coset space } |G/H|.
                   \\\\ \\text{Denoted by } [G:H].
      `
    },
    {
      number: 25,
      term: "Direct Product of Groups",
      definition: `\\text{Let } G_1, G_2 \\text{ be groups with } g_1 \\in G_1 \\text{ and } g_2 \\in G_2.
                   \\\\ \\text{The direct product } G_1 \\times G_2
                   \\\\ \\text{is the group of ordered pairs } (g_1, g_2)
                   \\\\ \\text{with the binary operation }
                   \\\\ (g_1, g_2) \\cdot (h_1, h_2) = (g_1h_1, g_2h_2)
                   \\\\ \\text{called the cartesian product}
                   \\\\ \\
                   \\\\ \\text{For example the point } (1, 2)
                   \\\\ \\text{is an element in } \\R^2 
                   \\\\ \\text{and } \\R^2 = \\R \\times \\R.
      `
    },
    {
      number: 26,
      term: "Ring",
      definition: `\\text{A ring is a set } R 
                   \\\\ \\text{equipped with two associative binary operations}
                   \\\\ +: R \\times R \\to R, 
                   \\\\ \\cdot: R \\times R \\to R 
                   \\\\ \\text{ satisfying:}
                   \\\\ \\
                   \\\\ \\ 1) \\ (R, +) \\text{ is an abelian group}
                   \\\\ \\
                   \\\\ \\ 2) \\ \\ \\forall a, b, c \\in R, 
                   \\\\ \\ \\ \\ \\ \\ \\ (a + b) \\cdot c = (a \\cdot c) + (b \\cdot c)
                   \\\\ \\ \\ \\ \\ \\ \\ a \\cdot (b + c) = (a \\cdot b) + (a \\cdot c).
      `
    },
    {
      number: 27,
      term: `Commutative Ring`,
      definition: `\\text{A ring } R \\text{ is commutative if}
                   \\\\ x y = y x \\ \\ \\forall x,y \\in \\R.
      `
    },
    {
      number: 28,
      term: "Unital Ring",
      definition: `\\text{Put simply, a ring is unital if it has both neutral elements.}
                   \\\\ \\
                   \\\\ \\text{Let } (R,+,\\cdot) \\text{ be a ring.}
                   \\\\ \\text{We say } R \\text{ is unital if it has}
                   \\\\ \\text{a neutral element for the operation } \\cdot.
                   \\\\ \\
                   \\\\ \\text{We denote the neutral element of } (R, +) \\text{ with } 0
                   \\\\ \\text{and the neutral element of } (R, \\cdot) \\text{ with } 1
      `
    },
    {
      number: 29,
      term: "Zero Divisor",
      definition: `\\text{A non-zero element } x \\in R \\text{ is a zero divisor if}
                   \\\\ \\text{there exists another non-zero element } y \\in R
                   \\\\ \\text{such that } xy = 0.
                   \\\\ \\
                   \\\\ \\text{In non-commutative rings this is called the left zero-divisor.}
                   \\\\ \\text{In commutative rings}
                   \\\\ \\text{left and right zero-divisors are the same.}
      `
    },
    {
      number: 30,
      term: "Integral Domain",
      definition: `\\text{A Ring } R \\text{ is an integral domain if}
                   \\\\ R \\text{ is a untial commutative ring and}
                   \\\\ R \\text{ has no zero divisors}.
      `
    },
    {
      number: 31,
      term: "Division Ring",
      definition: `R \\text{ is a division ring if}
                   \\\\ R \\text{ is a unital ring and}
                   \\\\ (R-\\{0\\}, \\cdot) \\text{ is a group.}
                   \\\\ \\
                   \\\\ \\text{This is if every non-zero element}
                   \\\\ \\text{has a multiplicative inverse for this operation}
      `
    },
    {
      number: 32,
      term: "Field",
      definition: `\\text{A commutative division ring is called a field.}
      `
    },
    {
      number: 33,
      term: "Subring",
      definition: `\\text{Let } (R, +, \\cdot) \\text{ be a ring}
                   \\\\ \\text{A subset } S \\subseteq R \\text{ is called a subring if:}
                   \\\\ \\quad 1) \\ \\ (S, +) \\text{ is a subgroup of } (R, +)
                   \\\\ \\quad 2) \\ \\ \\forall x, y \\in S, \\text{ we have } x \\cdot y \\in S.
      `
    },
    {
      number: 34,
      term: "Ring Homomorphism",
      definition: `\\text{Let } R \\text{ and } S \\text{ be rings}
                   \\\\ \\text{and } \\phi: R \\to S \\text{ be a map}.
                   \\\\ \\text{We say } \\phi \\text{ is a ring homomorphism}
                   \\\\ \\text{if } \\forall a, b \\in R.
                   \\\\ \\quad 1) \\ \\ \\phi (a+b) = \\phi(a) + \\phi(b)
                   \\\\ \\quad 2) \\ \\ \\phi(ab) = \\phi(a)\\phi(b)
      `
    },
    {
      number: 35,
      term: "Kernel of Ring Homomorphism",
      definition: `\\text{Let } \\phi: R \\to S \\text{ be a ring homomorphism}.
                   \\\\ \\text{The kernel of } \\phi \\text{ is } \\ker(\\phi) = \\{ r \\in R \\ | \\ \\phi(r) = 0 \\}.
      `
    },
    {
      number: 36,
      term: "Ideal",
      definition: `\\text{Let } I \\leq R.
                   \\\\ I \\text{ is an ideal in } R
                   \\\\ \\text{if } \\forall a \\in R \\text{ and } x \\in I,
                   \\\\ \\text{we have } ax \\in I \\text{ and } xa \\in I.
                   \\\\ \\text{In this case we write } I \\trianglelefteq R.
                   \\\\ \\
                   \\\\ \\text{An ideal } I \\triangleleft R \\text{ is proper if } I \\neq R.
      `
    },
    {
      number: 37,
      term: "Maximal Ideal",
      definition: `I \\triangleleft R \\text{ is maximal if } I \\neq R,
                   \\\\ \\text{and if } J \\triangleleft R \\text{ s.t. } I \\subseteq J \\subseteq R,
                   \\\\ \\text{then either } J = I \\text{ or } J = R.
      `
    },
    {
      number: 38,
      term: "Polynomial Ring",
      definition: `\\text{The polynomial ring } \\R[x] 
                   \\\\ \\text{has polynomial elements of the form}
                   \\\\ p(x) = a_nx^n + a_{n-1}x^{n-1} + ... + a_1 x + a_0
                   \\\\ \\text{with } a_0, a_1, ..., a_n \\in \\R \\text{ and } a_n \\neq 0.
      `
    },
    {
      number: 39,
      term: "Division Algorithm",
      definition:`\\text{Given polynomials, } p(x) \\text{ and } q(x)
                  \\\\ \\text{there are polynomials } a(x), r(x) 
                  \\\\ \\text{s.t. } q(x) = p(x) a(x) + r(x).
                  \\\\ \\text{Where either } r(x) = 0 \\text{ or } \\deg(r(x)) \\leq \\deg(p(x)). 
      `
    },
    {
      number: 40,
      term: "Principal Ideal",
      definition: `\\text{A principal ideal } \\langle x \\rangle \\text{ is an ideal in } 
                   \\\\ \\text{a commutative ring } R \\text{ generated by } x \\in R
                   \\\\ \\text{with } \\langle x \\rangle = \\{rx \\ | \\ r \\in R \\}.
                   \\\\ \\
                   \\\\ \\text{For example, } \\langle 6 \\rangle \\text{ is a principal ideal.}
                   \\\\ \\text{Because } \\langle 6 \\rangle = \\{n \\cdot 6 \\ | \\ n \\in \\Z \\} 
      `
    },
    {
      number: 41,
      term: "Principal Ideal Domain (PID)",
      definition: `\\text{A PID is an integral domain } R
                   \\\\ \\text{s.t. every ideal of } R \\text{ is principal}.
      `
    },
    {
      number: 42,
      term: "Divides Notation",
      definition: `\\text{Let } R \\text{ be a ring and } 0 \\neq a, x \\in R.
                   \\\\ \\text{We write } a | x 
                   \\\\ \\text{iff } \\ \\exists b \\in R \\text{ s.t. } x = ab.
                   \\\\ \\
                   \\\\ 3 | 6 \\text{ becase } 3 \\cdot 2 = 6.
      `
    },
    {
      number: 43,
      term: "Invertible Element",
      definition: `\\text{An element } a \\in R \\text{ is invertible}
                   \\\\ \\text{if there exists an element } b \\in R 
                   \\\\ \\text{s.t. } ab = 1.
                   \\\\ \\
                   \\\\ \\text{An element } a \\in \\Z_n \\text{ is invertible iff}
                   \\\\ \\text{} \\gcd(a, n) = 1.
                   \\\\ \\
                   \\\\ \\text{If } n \\text{ is prime}
                   \\\\ \\text{then every element in } \\Z_n \\text{ is invertible}
                   \\\\ \\
                   \\\\ \\text{For example,}
                   \\\\ \\text{in } \\Z_6 \\text{ both } 1 \\text{ and } 5 \\text{ are invertible.}
                   \\\\ 1 \\cdot 1 \\equiv 1 \\pmod{6} 
                   \\\\ 5 \\cdot 5 = 25 \\equiv 1 \\pmod{6}
                   \\\\ \\text{inverse of 1 is 1 and inverse of 5 is 5.}

      `
    },
    {
      number: 44,
      term: "Prime Element",
      definition: `\\text{Let } R \\text{ be a commutative ring.}
                   \\\\ \\text{An element } p \\in R \\text{ is said to be prime if}
                   \\\\ \\text{it is not the zero element or the one element}
                   \\\\ \\text{and whenever } p | ab \\ \\forall a, b \\in R, \\text{ then } p | a \\text{ or } p | b.
      `
    },
    {
      number: 45,
      term: "Irreducible/Prime Element",
      definition: `\\text{Let R be an ID.}
                   \\\\ \\text{A non-zero and non-invertible (not one) element } x \\in R 
                   \\\\ \\text{is called irreducible iff whenever } a, b \\in R \\text{ and } x = ab,
                   \\\\ \\text{then either } a \\text{ is invertible or } b \\text{ is invertible.}
                   \\\\ \\
                   \\\\ \\text{This is saying that} 
                   \\\\ \\text{an irreducible element cannot be factored}
                   \\\\ \\text{as two non-invertible elements.}
                   \\\\ \\
                   \\\\ \\text{In Unique Factor Domains (UFDs)}
                   \\\\ \\text{irreducable and prime is the same.}
                   \\\\ \\text{So for our purposes treat them as having both properties.}
                   

      `
    },
    {
      number: 46,
      term: "Prime Ideal",
      definition: `\\text{Let } R \\text{ be an ID.}
                   \\\\ \\text{A proper ideal } I \\triangleleft R \\text{ is called prime}
                   \\\\ \\text{iff whenever } ab \\in R \\text{ and } ab \\in I 
                   \\\\ \\text{then } \\text{either } a \\in I \\text{ or } b \\in I.
                   \\\\ \\
                   \\\\ \\text{For example,}
                   \\\\ 6 \\Z \\trianglelefteq \\Z \\text{ is not a prime ideal.}
                   \\\\ \\text{By choosing } 2, 3 \\in \\Z, \\text{ we have } 2 \\cdot 3 \\in \\Z \\text{ and } 2 \\cdot 3 \\in 6 \\Z.
                   \\\\ \\text{However, neither } 2 \\text{ or } 3 \\text{ are in } 6\\Z.
                   \\\\ \\
                   \\\\ 7 \\Z \\text{ is an example of a prime ideal.}
                   \\\\ \\text{Since 7 is a prime integer, its only factors are 1 and 7.}
      `
    },
    {
      number: 47,
      term: "Group Action",
      definition: `\\text{Let } G \\text{ be a group and let } X \\text{ be a set.}
                   \\\\ \\text{An action of } G \\text{ on } X \\text{ is}
                   \\\\ \\text{a group homomorphism } \\alpha: G \\to S_X.
                   \\\\ \\
                   \\\\ \\text{For each } g \\in G \\text{ and } x \\in X 
                   \\\\ \\text{we denote } gx = \\alpha(g)(x).
                   \\\\ \\
                   \\\\ \\text{An example is rotations of a snowflake.}
      `
    },
    {
      number: 48,
      term: "Kernel of Action",
      definition: `\\text{The kernel of the action is } 
                   \\\\ \\ker(\\alpha) = \\{g \\in G \\ | \\ gx = x \\ \\ \\forall x \\in X \\}
                   \\\\ \\
                   \\\\ \\text{In other words, the kernel is the set of} 
                   \\\\ \\text{elements of G that when acted upon x dont change x.}
                   \\\\ \\
                   \\\\ \\text{For example, taking the group } \\Z_6.
                   \\\\ \\text{and the set } \\Z_3. \\text{ Let } n \\in \\Z_6 \\text{ and } x \\in \\Z_3.
                   \\\\ \\text{Define the action } gx \\coloneqq (n+x) \\pmod{3}.
                   \\\\ \\ker(\\alpha) = \\{ 0, 3 \\}.
                   \\\\ \\
                   \\\\ \\text{If } n = 0, \\text{ then } 0 \\cdot x = (0+x) \\pmod{3} = x.
                   \\\\ \\text{So 0 is in the kernel.}
                   \\\\ \\
                   \\\\ \\text{If } n = 1, \\text{ then } 1 \\cdot 0 = (1+0) \\pmod{3} = 1.
                   \\\\ \\text{So 1 is not in the kernel.}
      `
    },
    {
      number: 49,
      term: "Faithful Action",
      definition: `\\text{An action is faithful if the kernel is trivial.}
                   \\\\ \\
                   \\\\ \\text{If } \\forall g \\in G \\text{ where } g \\neq e, \\ \\exists x \\in X \\text{ s.t. } gx \\neq x,
                   \\\\ \\text{then the action is faithful.}
                   \\\\ \\
                   \\\\ \\text{Or in other words, whenever } \\ker = \\{e\\}.
                   \\\\ \\
                   \\\\ \\text{So when an action is faithful,}
                   \\\\ \\text{we can tell different elements of } G \\text{ apart.}
                   \\\\ \\
                   \\\\ \\text{In the previous example of } G = \\Z_6 \\text{ and } X = \\Z_3
                   \\\\ \\text{the action of mod 3 addition is not faithful.}
                   \\\\ \\text{Because } \\ker(\\alpha) = \\{ 0, 3 \\} \\neq \\{0\\}.
                   \\\\ \\
                   \\\\ \\text{An example of a faithful action would be}
                   \\\\ gx \\coloneqq (g+x) \\pmod{3} 
                   \\\\ \\text{with } G = Z_3 \\text{ and } X = \\{1 \\}.
                   \\\\ 0 \\cdot 1 = (0+1) \\pmod{3} = 1
                   \\\\ 1 \\cdot 1 = (1+1) \\pmod{3} = 2
                   \\\\ 2 \\cdot 1 = (2+1) \\pmod{3} = 3
      `
    },
    {
      number: 50,
      term: "Free Action",
      definition: `\\text{An action is free if}
                   \\\\ \\forall g \\in G \\text{ where } g \\neq e, \\text{ every } x \\in X \\text{ satisfies } gx \\neq x.
                   \\\\ \\
                   \\\\ \\text{For example, choose}
                   \\\\ G = GL_n(\\R) \\text{ and } X = \\R^n.
                   \\\\ \\text{Let } A \\in G \\text{ and } v \\in X. 
                   \\\\ \\text{Define } Av \\coloneqq Av \\text{ (matrix multiplication)}.
                   \\\\ \\
                   \\\\ \\text{This is faithful since every matrix} 
                   \\\\ \\text{is a unique linear transformation.}
                   \\\\ \\
                   \\\\ \\text{However, the action is not free because}
                   \\\\ \\text{any matrix multiplied by the zero vector is the zero vector}.
      `
    },
    {
      number: 51,
      term: "G-set",
      definition: `\\text{A G-set is a set} X 
                   \\\\ \\text{alongside a group action of a group } G \\text{ on } X. 
      `
    },
    {
      number: 52,
      term: "G-orbits",
      definition: `\\text{The G-orbits of } x \\text{ is the set}
                   \\\\ Gx = \\{ gx \\ | \\ g \\in G \\}.
                   \\\\ \\
                   \\\\ \\text{Can be thought of as the set of positions}
                   \\\\ \\text{you can move } x \\text{ to by applying group elements.} 
      `
    },
    {
      number: 53,
      term: "Stabilizer",
      definition: `\\text{The stabilizer of } x \\text{ is the set}
                   \\\\ G_x = \\{ g \\in G \\ | \\ gx = x \\}
                   \\\\ \\
                   \\\\ \\text{The set of elements of G}
                   \\\\ \\text{that don't move our given } x.
                   \\\\ \\
                   \\\\ \\text{The kernel is the set of elements of } G
                   \\\\ \\text{that don't move any } x.
                   \\\\ \\text{So } \\ker \\subseteq G_x.
      `
    },
    {
      number: 54,
      term: "Fixed Points",
      definition: `\\text{Given a G-set } X, \\text{ the set of fixed points is}
                   \\\\ \\text{denoted as } X^G = \\{x \\in X \\ | \\ gx = x \\ \\ \\forall g \\in G \\}.
                   \\\\ \\
                   \\\\ \\text{For example, let}
                   \\\\ G = S_3 \\text{ and } X = \\R[x_1, x_2, x_3].
                   \\\\ \\text{For } \\sigma \\in S_3 \\text{ and } p(x_1, x_2, x_3) \\in \\R[x_1, x_2, x_3]
                   \\\\ \\text{Define } \\sigma p \\coloneqq p(x_{\\sigma(1)}, x_{\\sigma(2)}, x_{\\sigma(3)})
                   \\\\ \\text{In other words the action is plugging the subscript of each variable into}
                   \\\\ \\text{our bijective function / permutation and giving us another one of the subscripts.}
      `
    }

  ];
  return (
    <div>
      <div className="mb-4 sm:mb-6 p-3 sm:p-4 bg-gray-50 rounded-lg border border-gray-200">
        <p className="text-gray-700 text-sm sm:text-base">
          Catalog of Definitions. Used Fraleigh's "A First Course in Abstract Algebra" as reference.
        </p>
      </div>
      {definitions.map((def) => (
        <DefinitionCard
          key={def.number}
          number={def.number}
          term={def.term}
          definition={def.definition}
          image={def.image}
          imageAlt={def.imageAlt}
        />
      ))}
      <div className="mt-8 flex flex-col items-center">
        <Image
          src="/guatemamas.jpg"
          alt="Guatemamas"
          width={4032}
          height={3024}
          className="rounded-lg"
        />
        <p className="mt-2 text-gray-600 text-sm italic">Up the road to Santa Cruz la Laguna, Guatemala</p>
        <p className="text-gray-600 text-sm italic">You're almost there!</p>
      </div>
    </div>
  );
}
