import DefinitionCard from "../components/DefinitionCard";

export default function DefinitionsPage() {
  // Example definitions - replace with your actual definitions
  const definitions = [
    {
      number: 1,
      term: "Group",
      definition: `\\text{A group is a set } G \\text{ together with a binary operation } * \\text{ such that:} 
                  \\\\ \\quad 1. \\text{ (Closure) } \\forall a, b \\in G, a * b \\in G 
                  \\\\ \\quad 2. \\text{ (Associativity) } \\forall a, b, c \\in G, (a * b) * c = a * (b * c) 
                  \\\\ \\quad 3. \\text{ (Identity) } \\exists e \\in G \\text{ such that } \\forall a \\in G, e * a = a * e = a 
                  \\\\ \\quad 4. \\text{ (Inverse) } \\forall a \\in G, \\exists a^{-1} \\in G \\text{ such that } a * a^{-1} = a^{-1} * a = e,`,
    },
    {
      number: 2,
      term: "Subgroup",
      definition: "\\text{Let } G \\text{ be a group. A subset } H \\subseteq G \\text{ is a subgroup if:} \\\\ \\quad 1. \\text{ The identity } e \\in H \\\\ \\quad 2. \\text{ If } a, b \\in H, \\text{ then } ab \\in H \\\\ \\quad 3. \\text{ If } a \\in H, \\text{ then } a^{-1} \\in H",
    },

    {
      number: 4,
      term: "Homomorphism",
      definition: `\\text{Let } G \\text{ and } K \\text{ be two groups.}
                  \\\\ \\text{A map } \\phi: G \\to K \\text{ is called a homomorphism}
                  \\\\ \\text{if } \\forall a, b \\in G, \\phi(ab) = \\phi(a)\\phi(b)
                  \\\\ \\
                  \\\\ \\text{To be homomorphic haiku:}
                  \\\\ \\
                  \\\\ \\text{operate then map}
                  \\\\ \\text{must give the same result as}
                  \\\\ \\text{map then operate}
      `,
    },
    {
      number: 5,
      term: "Isomorphism",
      definition: `\\text{An isomorphism is a bijective homomorphism.}
                   \\\\ \\text{Written as } G \\cong K, \\text{ where } G \\text{ and } K \\text{ are groups}.
      `
    },
    {
      number: 6,
      term: "Kernel of a Homomorphism",
      definition: `\\text{Let } \\phi: G \\to K \\text{ be a homomorphism between groups } G \\text{ and } K.
                  \\\\ \\text{The kernel of } \\phi \\text{ is the set:}
                  \\\\ \\ker(\\phi) = \\{ x \\in G \\ | \\ \\phi(x) = e_K \\}`,
    },
    {
      number: 7,
      term: "Normal Subgroup",
      definition: `\\text{A subgroup } H \\text{ of a group } G \\text{ is called normal }( H \\trianglelefteq G )
                   \\\\ \\text{if } \\forall g \\in G, \\forall h \\in H, ghg^{-1} \\in H.
                   \\\\ \\
                   \\\\ H \\trianglelefteq G \\text{ if } H \\subseteq G.
                   \\\\ H \\triangleleft G \\text{ if } H \\subset G.
                  `,
    },
    {
      number: 8,
      term: "Generating Set",
      definition: `\\text{Let } G \\text{ be a group and let } S \\subseteq G \\text{ be nonempty.}
                   \\\\ \\text{Denote } S^{-1} = \\{ a^{-1} | a \\in S \\}.
                   \\\\ \\text{Then } \\langle S \\rangle = \\{x_1x_2 ... x_n \\ | \\ n \\in \\N, x_i \\in S \\cup S^{-1} \\cup \\{e\\}\\}.
                   \\\\ \\
                   \\\\ \\langle S \\rangle \\text{ is created by choosing different } n \\text{'s} 
                   \\\\ \\text{and finding the product of 1 through n elements of } S \\cup S^{-1} \\cup \\{e\\}.
                   \\\\ \\
                   \\\\ \\text{For a single element:}
                   \\\\ \\langle g \\rangle = \\{g^n \\ | \\ n \\in \\Z \\}
      `
    },
    {
      number: 9,
      term: "Finitely Generated Group",
      definition: `\\text{A group is finitely generated if}
                   \\\\ \\text{there exists a finite nonempty subset of } S 
                   \\\\ \\text{s.t. } G \\text{ is generated by } S.
                   \\\\ \\text{In other words, } G = \\langle S \\rangle.
      `
    },
    {
      number: 10,
      term: "Cyclic Group",
      definition: `\\text{A group } G \\text{ is cyclic if }
                   \\\\ \\text{the group is generated by a single element. }
                   \\\\ \\text{i.e. if } G = \\langle a \\rangle \\text{ for some } a \\in G.
      `
    },
    {
      number: 11,
      term: "Relation",
      definition: `\\text{Let } X \\text{ be a set.}
                   \\\\ \\text{A relation on X is a subset of } X \\times X.
                   \\\\ \\
                   \\\\ \\text{In other words, a relation is an ordered pair}.
                   \\\\ \\
                   \\\\ \\text{For example, the point } (1, 2) \\text{ relates 1 and 2 in } \\R^2.
                   \\\\ \\text{You would write } 1 \\sim 2 \\text{ in this case.}
      `
    },
    {
      number: 12,
      term: "Properties of Relations",
      definition: `\\def\\circled#1{\\raisebox{.5pt}{\\textcircled{\\raisebox{-.9pt} {#1}}}}

                   \\text{A relation on } X \\text{ is said to be:}
                   \\\\ \\circled{1} \\text{ reflexive: if } x \\sim x \\ \\ \\forall x \\in X
                   \\\\ \\circled{2} \\text{ symmetric: if } x \\sim y \\implies y \\sim x \\ \\ \\forall x,y \\in X.
                   \\\\ \\circled{3} \\text{ transitive: if } x \\sim y \\wedge y \\sim z \\implies x \\sim z
                   \\\\ \\ \\ \\ \\ \\ \\forall x, y, z \\in X
                   \\\\ \\circled{4} \\text{ anti-symmetric: if } x \\sim y \\wedge y \\sim x \\implies x = y 
                   \\\\ \\ \\ \\ \\ \\ \\forall x, y \\in X.
      `
    },
    {
      number: 13,
      term: "Order Relation",
      definition: `\\text{An order relation (or partial order) on } X
                   \\\\ \\text{is a relation that is reflexive, antisymmetric, and transitive.}
                   \\\\ \\
                   \\\\ a \\leq b \\text{ and } a \\ | \\ b \\text{ (a "divides" b)}
                   \\\\ \\text{are examples of order relations.}
      `
    },
    {
      number: 14,
      term: "Equivalence Relation",
      definition: `\\text{An equivalence relation on } X
                   \\\\ \\text{is a relation that is reflexive, symmetric, and transitive.}
                   \\\\ \\
                   \\\\ \\text{For example, say two M} \\& \\text{Ms are the same if they have the same color}
                   \\\\ \\text{This is denoted as } a \\sim b \\iff (a \\text{ has same color as } b).
                   \\\\ \\
                   \\\\ \\text{Considering different equivalence relations on a set gives different partitions.}
                   \\\\ \\text{So a single set can be observed in many different ways.}
      `
    },
    {
      number: 15,
      term: "Equivalence Class",
      definition: `\\text{Given an equivalence relation } \\sim \\text{ on a set } X, 
                  \\\\ \\text{the equivalence class of } x \\in X \\text{ is the set:}
                  \\\\ [x] = \\{ y \\in X \\ | \\ x \\sim y \\}
                  \\\\ \\
                  \\\\ \\text{This was presented as a theorem:}
                  \\\\ \\quad 1) \\ \\ \\forall x, y \\in X
                  \\\\ \\quad \\quad \\ \\ \\text{if } x \\sim y \\text{ then } [x] = [y]
                  \\\\ \\quad \\quad \\ \\ \\text{if } x \\not \\sim y \\text{ then } [x] \\cap [y]  = \\empty.
                  \\\\ \\quad 2) \\ \\ \\bigcup_{x \\in X} [x] = X.
                  `
    },
    {
      number: 16,
      term: "Left Coset",
      definition: `\\text{Let } H \\leq G \\text{ and } x \\in G.
                   \\\\ \\text{The set } \\{ xh \\ | \\ h \\in H \\} \\text{ is called the left coset by } x.
                   \\\\ \\text{Written as } xH.
      `
    },
    {
      number: 17,
      term: "Automorphism",
      definition: `\\text{An automorphism is an isomorphism that maps from } G \\text{ to } G.
                   \\\\ \\text{Aut}(G) \\text{ is the set of all automorphisms of G.}
      `
    },
    {
      number: 18,
      term: "Inner Automorphism",
      definition: `\\text{An inner automorphism is an automorphism } 
                   \\\\ \\text{of the form } \\phi_g: G \\to G, \\text{ defined by } \\phi_g(x) = gxg^{-1} \\ \\text{ for } x, g \\in G.
                   \\\\ \\
                   \\\\ \\text{We denote }\\text{Inn}(G) = \\{\\phi_g \\ | \\ g \\in G \\} 
                   \\\\ \\text{as the set of all inner automorphisms of } G.
      `
    },
    {
      number: 19,
      term: "Symmetric Group",
      definition: `\\text{Let } X \\text{ be a set. Let } S_X = \\{f: X \\to X \\ | \\ f \\text{ is bijective} \\}.
                   \\\\ S_X \\text{ with composition is called the symmetric group.} 
                   \\\\ \\
                   \\\\ \\text{For } n \\in \\N \\text{ and } X = \\{ 1, 2, ..., n \\},  
                   \\\\ \\text{We denote } S_n \\text{ for } S_X.
                   \\\\ \\
                   \\\\ \\text{For example } S_2 \\text{ is the group of bijective functions over }
                   \\\\ X = \\{ 1, 2 \\}, \\text{and only has two elements: the identity function and a single transposition}.
                   \\\\ \\text{In other words the only actions you can do in } S_2 \\text{ is stay in place or swap places.}
      `
    },
    {
      number: 20,
      term: "Permutation",
      definition: `\\text{A permutation is a bijective mapping from a set onto itself}
      `
    },
    {
      number: 21,
      term: "Transposition",
      definition: `\\text{Let } n \\geq 2.
                   \\\\ \\text{A transposition is a permutation } \\tau \\in S_n
                   \\\\ \\text{of the form } (i \\ j) \\text{ for } 1 \\leq i \\neq j \\leq n.

      `
    },
    {
      number: 22,
      term: "Even or Odd Permutation",
      definition: `\\text{A permutation is called even if}
                   \\\\ \\text{it is a product of an even number of transpositions.}
                   \\\\ \\
                   \\\\ \\text{A permutation is called odd if}
                   \\\\ \\text{it is a product of an odd number of transpositions.}
      `
    },
    {
      number: 23,
      term: "Index",
      definition: `\\text{Let } H \\leq G. 
                   \\\\ \\text{The index of H in G is} 
                   \\\\ \\text{the cardinality of the coset space } |G/H|.
                   \\\\ \\text{Denoted by } [G:H].
      `
    },
    {
      number: 24,
      term: "Direct Product of Groups",
      definition: `\\text{Let } G_1, G_2 \\text{ be groups with } g_1 \\in G_1 \\text{ and } g_2 \\in G_2.
                   \\\\ \\text{The direct product } G_1 \\times G_2
                   \\\\ \\text{is the group of ordered pairs } (g_1, g_2)
                   \\\\ \\text{with the binary operation }
                   \\\\ (g_1, g_2) \\cdot (h_1, h_2) = (g_1h_1, g_2h_2)
                   \\\\ \\text{called the cartesian product}
                   \\\\ \\
                   \\\\ \\text{For example the point } (1, 2)
                   \\\\ \\text{is an element in } \\R^2 
                   \\\\ \\text{and } \\R^2 = \\R \\times \\R.
      `
    },
    {
      number: 25,
      term: "Ring",
      definition: `\\text{A ring is a set } R 
                   \\\\ \\text{equipped with two associative binary operations}
                   \\\\ +: R \\times R \\to R, 
                   \\\\ \\cdot: R \\times R \\to R 
                   \\\\ \\text{ satisfying:}
                   \\\\ \\
                   \\\\ \\ 1) \\ (R, +) \\text{ is an abelian group}
                   \\\\ \\
                   \\\\ \\ 2) \\ \\ \\forall a, b, c \\in R, 
                   \\\\ \\ \\ \\ \\ \\ \\ (a + b) \\cdot c = (a \\cdot c) + (b \\cdot c)
                   \\\\ \\ \\ \\ \\ \\ \\ a \\cdot (b + c) = (a \\cdot b) + (a \\cdot c).
      `
    },
    {
      number: 26,
      term: `Commutative Ring`,
      definition: `\\text{A ring } R \\text{ is commutative if}
                   \\\\ x y = y x \\ \\ \\forall x,y \\in \\R.
      `
    },
    {
      number: 27,
      term: "Unital Ring",
      definition: `\\text{Put simply, a ring is unital if it has both neutral elements.}
                   \\\\ \\
                   \\\\ \\text{Let } (R,+,\\cdot) \\text{ be a ring.}
                   \\\\ \\text{We say } R \\text{ is unital if it has}
                   \\\\ \\text{a neutral element for the operation } \\cdot.
                   \\\\ \\
                   \\\\ \\text{We denote the neutral element of } (R, +) \\text{ with } 0
                   \\\\ \\text{and the neutral element of } (R, \\cdot) \\text{ with } 1
      `
    },
    {
      number: 28,
      term: "Zero Divisor",
      definition: `\\text{A non-zero element } x \\in R \\text{ is a zero divisor if}
                   \\\\ \\text{there exists another non-zero element } y \\in R
                   \\\\ \\text{such that } xy = 0.
                   \\\\ \\
                   \\\\ \\text{In non-commutative rings this is called the left zero-divisor.}
                   \\\\ \\text{In commutative rings left and right zero-divisors are the same.}
      `
    },
    {
      number: 29,
      term: "Integral Domain",
      definition: `\\text{A Ring } R \\text{ is an integral domain if}
                   \\\\ R \\text{ is a untial commutative ring and}
                   \\\\ R \\text{ has no zero divisors}.
      `
    },
    {
      number: 30,
      term: "Division Ring",
      definition: `R \\text{ is a division ring if}
                   \\\\ R \\text{ is a unital ring and}
                   \\\\ (R-\\{0\\}, \\cdot) \\text{ is a group.}
                   \\\\ \\
                   \\\\ \\text{This is if every non-zero element}
                   \\\\ \\text{has a multiplicative inverse for this operation}
      `
    },
    {
      number: 31,
      term: "Field",
      definition: `\\text{A commutative division ring is called a field.}
      `
    },
    {
      number: 32,
      term: "Subring",
      definition: `\\text{Let } (R, +, \\cdot) \\text{ be a ring}
                   \\\\ \\text{A subset } S \\subseteq R \\text{ is called a subring if:}
                   \\\\ 1) \\ \\ (S, +) \\text{ is a subgroup of } (R, +)
                   \\\\ 2) \\ \\ \\forall x, y \\in S, \\text{ we have } x \\cdot y \\in S.
      `
    },
    {
      number: 33,
      term: "Ring Homomorphism",
      definition: `\\text{Let } R \\text{ and } S \\text{ be rings}
                   \\\\ \\text{and } \\phi: R \\to S \\text{ be a map}.
                   \\\\ \\text{We say } \\phi \\text{ is a ring homomorphism}
                   \\\\ \\text{if } \\forall a, b \\in R.
                   \\\\ \\quad 1) \\ \\ \\phi (a+b) = \\phi(a) + \\phi(b)
                   \\\\ \\quad 2) \\ \\ \\phi(ab) = \\phi(a)\\phi(b)
      `
    },
    {
      number: 34,
      term: "Kernel of Ring Homomorphism",
      definition: `\\text{Let } \\phi: R \\to S \\text{ be a ring homomorphism}.
                   \\\\ \\text{The kernel of } \\phi \\text{ is } \\ker(\\phi) = \\{ r \\in R \\ | \\ \\phi(r) = 0 \\}.
      `
    },
    {
      number: 35,
      term: "Ideal",
      definition: `\\text{Let } I \\leq R.
                   \\\\ I \\text{ is an ideal in } R
                   \\\\ \\text{if } \\forall a \\in R \\text{ and } x \\in I,
                   \\\\ \\text{we have } ax \\in I \\text{ and } xa \\in I.
                   \\\\ \\text{In this case we write } I \\trianglelefteq R.
                   \\\\ \\
                   \\\\ \\text{An ideal } I \\triangleleft R \\text{ is proper if } I \\neq R.
      `
    },
    {
      number: 36,
      term: "Maximal Ideal",
      definition: `I \\triangleleft R \\text{ is maximal if } I \\neq R,
                   \\\\ \\text{and if } J \\triangleleft R \\text{ s.t. } I \\subseteq J \\subseteq R,
                   \\\\ \\text{then either } J = I \\text{ or } J = R.
      `
    },
    {
      number: 37,
      term: "Polynomial Ring",
      definition: `\\text{The polynomial ring } \\R[x] 
                   \\\\ \\text{has polynomial elements of the form}
                   \\\\ p(x) = a_nx^n + a_{n-1}x^{n-1} + ... + a_1 x + a_0
                   \\\\ \\text{with } a_0, a_1, ..., a_n \\in \\R \\text{ and } a_n \\neq 0.
      `
    },
    {
      number: 38,
      term: "Division Algorithm",
      definition:`\\text{Given polynomials, } p(x) \\text{ and } q(x)
                  \\\\ \\text{there are polynomials } a(x), r(x) 
                  \\\\ \\text{s.t. } q(x) = p(x) a(x) + r(x).
                  \\\\ \\text{Where either } r(x) = 0 \\text{ or } \\deg(r(x)) \\leq \\deg(p(x)). 
      `
    },
    {
      number: 39,
      term: "Principal Ideal",
      definition: `\\text{FUN}
      `
    },
    {
      number:40,
      term: "Principal Ideal Domain (PID)",
      definition: `\\text{A PID is an integral domain } R
                   \\\\ \\text{s.t. every ideal of } R \\text{ is principal }
      `
    },
    {
      number: 1000,
      term: "Euclid's Lemma",
      definition: `\\text{Let } R \\text{ be a commutative ring.}
                   \\\\ \\text{An element } p \\in R \\text{ is said to be prime if}
                   \\\\ \\text{it is not the zero element or a unit (one)}
                   \\\\ \\text{and whenever } p | ab \\ \\forall a, b \\in R, \\text{ then } p | a \\text{ or } p | b.
      `
    },
    {
      number: 1001,
      term: "Prime Ideal",
      definition: `\\text{Let R be an ID.}
                   \\\\ \\text{A non-zero and non-invertible (not one) element } x \\in R 
                   \\\\ \\text{is called prime iff whenever } a, b \\in R \\text{ and } x = ab,
                   \\\\ \\text{then either }

      `
    }
  ];
  return (
    <div>
      <div className="mb-4 sm:mb-6 p-3 sm:p-4 bg-gray-50 rounded-lg border border-gray-200">
        <p className="text-gray-700 text-sm sm:text-base">
          Catalog of Definitions. Used Fraleigh's "A First Course in Abstract Algebra" as reference.
        </p>
      </div>
      {definitions.map((def) => (
        <DefinitionCard
          key={def.number}
          number={def.number}
          term={def.term}
          definition={def.definition}
        />
      ))}
    </div>
  );
}
